### ISSUE TITLE
Error with webpack installation

### ISSUE THREAD

**Issue by lohnguyen** [zendesk/volunteer_portal#179]
After setting up the Google OAuth2 and started to deploy on Heroku I got the following error:

```
Webpacker is installed 🎉 🍰
       Using /tmp/build_10814255313d814194b1940b8a2ac519/config/webpacker.yml file for setting up webpack paths
       [Webpacker] Compiling assets 🎉
       [Webpacker] Compilation Failed
       ./node_modules/.bin/webpack --config /tmp/build_10814255313d814194b1940b8a2ac519/config/webpack/production.js
       
       ./bin/webpack:28:in `exec': No such file or directory - ./node_modules/.bin/webpack (Errno::ENOENT)
       	from ./bin/webpack:28:in `block in <main>'
       	from ./bin/webpack:26:in `chdir'
       	from ./bin/webpack:26:in `<main>'
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

I tried to install yarn and update my ruby version, but none of those solutions seemed to help.

Any advice is welcomed!

**Comment by xuebingli** [comment]
Do you have both `ruby` and `nodejs` buildpacks enabled on your Heroku project?

![Screen Shot 2019-08-04 at 3 36 02 pm](https://user-images.githubusercontent.com/1525352/62419888-a1c36980-b6cd-11e9-938e-e6b05e1016aa.png)

**Comment by lazyplatypus** [comment]
I think the issue is when we follow the link on the docs/deploy.md, we don’t have an option to add to build pack.
(https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fzendesk%2Fvolunteer_portal%2Fblob%2Fmaster%2Fdocs%2Fdeploy.md&template=https%3A%2F%2Fgithub.com%2Fzendesk%2Fvolunteer_portal%2Ftree%2Fmaster <https://dashboard.heroku.com/new?button-url=https://github.com/zendesk/volunteer_portal/blob/master/docs/deploy.md&template=https://github.com/zendesk/volunteer_portal/tree/master>) 

I am not sure if this Heroku link is working.

Best,
Daniel

**Comment by xuebingli** [comment]
Thanks for the link. The documentation may outdated. Let me look into it.

**Comment by xuebingli** [comment]
It appears the webpack (and `webpacker` gem) setup is not working anymore. I'll be able to investigate further on Aug 14th. 

The setup is outdated and this investigation may be an opportunity for upgrade.

**Comment by lazyplatypus** [comment]
Hey! I was wondering if there were any updates on this.

Best,
Daniel

**Comment by xuebingli** [comment]
Hi Daniel, I've created [a separate branch for webpack 4 upgrade](https://github.com/zendesk/volunteer_portal/tree/upgrade-webpack). It appears to work fine in initial tests. Please use the link below to try deployment with the said branch.

https://heroku.com/deploy?template=https://github.com/zendesk/volunteer_portal/tree/upgrade-webpack

**Comment by lazyplatypus** [comment]
This works! Thank you so much!
